Update Notify values for Feedback app on Staging
We've been seeing a Smokey failure on Staging:

```
@app-feedback
Feature: Feedback
  @worksonmirror
  Scenario: Check the frontend can talk to Content Store # features/apps/feedback.feature:5
    When I visit "/contact/govuk"                        # features/step_definitions/smokey_steps.rb:59
    Then I should see "Contact GOV.UK"                   # features/step_definitions/smokey_steps.rb:152
  @notcloudfront
  Scenario: Check "is this page useful?" email survey # features/apps/feedback.feature:10
    When I visit "/"                                  # features/step_definitions/smokey_steps.rb:59
    And I click to say the page is not useful         # features/step_definitions/feedback_steps.rb:24
    And I submit the email survey signup form         # features/step_definitions/feedback_steps.rb:48
    Then I see the feedback confirmation message      # features/step_definitions/feedback_steps.rb:55
      expected to find text "Thank you for your feedback" in "Skip to main content\nCookies on GOV.UK\nWe use some essential cookies to make this website work.\nWe’d like to set additional cookies to understand how you use GOV.UK, remember your settings and improve government services.\nWe also use cookies set by other sites to help us deliver content from their services.\nAccept additional cookies\nReject additional cookies\nView cookies\nGOV.UK\nNavigation menu\nMenu\nSearch GOV.UK\nGOV.UK\n-\nThe best place to find government services and information\nSearch\nSearch GOV.UK\nPopular on GOV.UK\nGet support with the cost of living\nFind out about help you can get with your energy bills\nFind a job\nUniversal Credit account: sign in\nCheck your National Insurance record\nCheck MOT history of a vehicle\nServices and information\nBenefits\nIncludes eligibility, appeals, tax credits and Universal Credit\nBirths, deaths, marriages and care\nParenting, civil partnerships, divorce and Lasting Power of Attorney\nBusiness and self-employed\nTools and guidance for businesses\nChildcare and parenting\nIncludes giving birth, fostering, adopting, benefits for children, childcare and schools\nCitizenship and living in the UK\nVoting, community participation, life in the UK, international projects\nCrime, justice and the law\nLegal processes, courts and the police\nDisabled people\nIncludes carers, your rights, benefits and the Equality Act\nDriving and transport\nIncludes vehicle tax, MOT and driving licences\nEducation and learning\nIncludes student loans, admissions and apprenticeships\nEmploying people\nIncludes pay, contracts, hiring and redundancies\nEnvironment and countryside\nIncludes flooding, recycling, farming and wildlife\nHousing and local services\nOwning or renting and council services\nMoney and tax\nIncludes debt and Self Assessment\nPassports, travel and living abroad\nIncludes renewing passports and travel advice by country\nVisas and immigration\nApply to visit, work, study, settle or seek asylum in the UK\nWorking, jobs and pensions\nIncludes holidays, finding a job and redundancy\nFeatured\nCost of Living Payment\nFind out payment dates and how to report a payment is missing.\nSelf Assessment\nFind out about Self Assessment tax returns and when they are due.\nNational Insurance\nCheck your record to see if you can add more contributions.\nGovernment activity\nFind out what the government is doing\nDepartments\nDepartments, agencies and public bodies\nResearch and statistics\nReports, analysis and official statistics\nNews\nNews stories, speeches, letters and notices\nPolicy papers and consultations\nConsultations and strategy\nGuidance and regulation\nDetailed guidance, regulations and rules\nTransparency documents\nData, Freedom of Information releases and corporate reports\nMore on GOV.UK\nHMRC services: sign in\nCheck MOT history of a vehicle\nTax your vehicle\nUniversal Credit\nForeign travel advice\nCheck your State Pension age\nChildcare account: sign in\nStudent finance: sign in\nSelf Assessment tax returns\nApply for a passport\nSorry, we’re unable to receive your message right now.\nIf the problem persists, we have other ways for you to provide feedback on the contact page.\nHelp us improve GOV.UK\nTo help us improve GOV.UK, we’d like to know more about your visit today. We’ll send you a link to a feedback form. It will take only 2 minutes to fill in. Don’t worry we won’t send you spam or share your email address with anyone.\nEmail address\nSend me the survey Cancel Don’t have an email address?\nServices and information\nBenefits Births, death, marriages and care Business and self-employed Childcare and parenting Citizenship and living in the UK Crime, justice and the law Disabled people Driving and transport Education and learning Employing people Environment and countryside Housing and local services Money and tax Passports, travel and living abroad Visas and immigration Working, jobs and pensions\nGovernment activity\nDepartments News Guidance and regulation Research and statistics Policy papers and consultations Transparency How government works Get involved\nSupport links\nHelp Privacy Cookies Accessibility statement Contact Terms and conditions Rhestr o Wasanaethau Cymraeg Government Digital Service\nAll content is available under the Open Government Licence v3.0, except where otherwise stated\n© Crown copyright". (However, it was found 1 time including non-visible text.) (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/feedback_steps.rb:56:in `/^I see the feedback confirmation message$/'
      features/apps/feedback.feature:14:in `I see the feedback confirmation message'
    And a request is sent to the feedback app         # features/step_definitions/feedback_steps.rb:59
```

This is reproducible by following the [steps](https://github.com/alphagov/smokey/blob/df6d92074166d45f882e07d2fb1012e43c7114a2/features/step_definitions/feedback_steps.rb)
on https://www.staging.publishing.service.gov.uk/.

Sentry error:
https://govuk.sentry.io/issues/3284227631/events/b371f720882f4d8091ce0373c7c355f9/?environment=staging&project=202223&query=is%3Aunresolved&referrer=previous-event&statsPeriod=7d&stream_index=0

```
AuthError: Invalid token: service has no API keys (Notifications::Client::AuthError)
```

In https://trello.com/c/cyw0yjuo/94-lock-down-access-to-all-of-govuks-notify-services,
I deleted a `GOV.UK (Staging)` trial service from Notify, as it
didn't appear to be in use (no sent emails). It was in fact being
used by Feedback, and its API token was in 'test' mode, i.e. it
would return API responses as if it had sent the emails, but not
actually send any emails.

I recreated the service and also created a new API token, which
I set in AWS Secrets Manager. New error:
https://govuk.sentry.io/issues/3284227631/events/628511fd6ebd406bb5c4d4d25250f323/?environment=staging&project=202223&query=is%3Aunresolved&referrer=next-event&statsPeriod=7d&stream_index=0

```
BadRequestError: Template not found (Notifications::Client::BadRequestError)
```

I then created a template in the service:
https://www.notifications.service.gov.uk/services/a351da26-20c5-4432-92f3-4058fd65cef0/templates/9295dc76-91f2-4436-b2ca-4e69a6bc9f23

...and updated the template ID in this commit.
The 'reply to' email address ID also needed updating, so I set a
Reply-To email address on the service and updated the var in this
commit too.

I'm hopeful that this will mean the template is found, the email
will be 'sent', there'll be no error in Feedback, and Smokey will
start passing again.

See related Slack thread: https://gds.slack.com/archives/CADKZN519/p1707310093647719